### ISSUE TITLE
Security Breach

### ISSUE THREAD

**Issue by ahmedhammad97** [ramikhafagi96/Youtube-Videos#1]
https://github.com/ramikhafagi96/Youtube-Videos/blob/12d9abe5903141d5c4ee563c34d6a1ffe3498dd1/src/api/youtube.js#L3

Never push a code containing your private access key to a public repo :D

Instead, move it to a json config file which is imported to the module, and add this config file to `.gitignore` ;) 

![image](https://user-images.githubusercontent.com/22353947/70007836-8df41b00-157a-11ea-8d17-b76a51eeb5c6.png)

**Comment by ramikhafagi96** [comment]
The issue is fixed, thanks a lot mate for the tip...much love <3

>
